### ISSUE TITLE
Implement the timeline section

### ISSUE THREAD

**Issue by mrmihi** [sliitsesc/sliitxtreme-web-2024#38]
## Design
![image](https://github.com/user-attachments/assets/d801718a-0dc9-4500-9d2a-7db58906cfdb)

## Acceptance Criteria
- The ongoing stage should have the glowing effect and is of solid border
- Others should have dashed border
- Ended events can have solid border, but not glowing

## Notes
Use the DaisyUI timeline component and modify with our styles. It would be easy

**Comment by pawan-live** [comment]
Completed. Better if someone can handle auto updating... You will need to refresh to get updates to the timeline section
