### ISSUE TITLE
Implement the Gallery section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/sliitxtreme-web-2024#64]
## Summary
Implement the gallery section that links to past competition facebook albums

## Design
![image](https://github.com/user-attachments/assets/f1fad7f2-8a5e-4fb8-b54b-c0bb2a353882)

## Acceptance Criteria
- Three album links with photos
- Opens in new tab
- On hover, grayscale image should be colored

**Comment by pawan-live** [comment]
Completed. Minor styles to be fixed ✅

**Comment by mrmihi** [comment]
Layout and styling fixed.
